jwt:
  secret: '3b884c26c9f0'
  expires: '1h'

http:
  port: 3000
  host: 'localhost'

oauth:
  client_id: '366367411998-7bgfgptmsotqtpe3fibuv0kuntucjedt.apps.googleusercontent.com'
  secret: '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'
